### PR TITLE
fix(#472): duplicate rows in get history

### LINKED ISSUE #472: Paging does not work in ZenBPM UI correctly
### Description

Paging compoonent on the History tab of the proecss instance details is showing correct number of pages (2), the page size is set to 10 and I have 11 records, but if I move to the second page, I still see the same number of records. It seems that the frontend is not executing any backend request (I do not see any activity in the dev tools)
Also, the backend requests do not reflect the currently set page size.

Image

Image

### Steps to Reproduce

I upload BPMN model
I execute an instance to reach the end state.
I look into the history and see that see that 11 elements were executed, I see page size 10, and two pages (so far all good)
I try to click on the second page, nothing happens. I try to change the paging size, nothing happens.

### Environment

_No response_

### Expected Behavior

_No response_

### PR DESCRIPTION
**Pull request by triskill**
closes #472

### CODE REVIEW

File: internal/sql/queries/flow_element_instance.sql [hunk 1]
```diff
@@ -29,6 +29,7 @@ JOIN flow_element_instance AS fei
     ON fei.process_instance_key = pi.key
 WHERE
     et.process_instance_key = @process_instance_key
+GROUP BY fei.key
```
[the remark this answers is not in the document]
Comment (triskill) [reply internal/sql/queries/flow_element_instance.sql]: now it is done in different way. - getting history just for one instance.

File: internal/sql/queries/process_instance.sql [hunk 2]
```diff
@@ -176,65 +176,93 @@ WHERE
...
+        et.element_id,
+        0         AS active_count,
+        0         AS incident_count,
+        0         AS completed_count,
+        COUNT(*) AS terminated_count
+    FROM execution_token AS et
+    WHERE et.process_instance_key IN (SELECT "key" FROM relevant_instances)
+      AND et.state = 4
+    GROUP BY et.element_id
 ),
```
[the remark this answers is not in the document]
Comment (triskill) [reply internal/sql/queries/process_instance.sql]: Ok, i amend it.

File: openapi/api.yaml [hunk 3]
```diff
@@ -2772,13 +2772,21 @@ components:
       required:
         - activeCount
         - incidentCount
+        - completedCount
+        - terminatedCount
       properties:
```
[the remark this answers is not in the document]
Comment (triskill) [reply openapi/api.yaml:2861]: ok, i amended it.

File: internal/sql/queries/process_instance.sql [hunk 4]
```diff
@@ -176,65 +176,59 @@ WHERE
...
+    CAST(SUM(active_count)     AS INTEGER) AS active_count,
+    CAST(SUM(incident_count)   AS INTEGER) AS incident_count,
+    CAST(SUM(completed_count)  AS INTEGER) AS completed_count,
+    CAST(SUM(terminated_count) AS INTEGER) AS terminated_count
+FROM (
+    SELECT element_id, active_count, incident_count, completed_count, terminated_count FROM token_stats
+    UNION ALL
+    SELECT element_id, active_count, incident_count, completed_count, terminated_count FROM incident_stats
+) AS combined
+GROUP BY element_id;
```
[the remark this answers is not in the document]
Comment (triskill) [reply internal/sql/queries/process_instance.sql:236]: we do not need more comments

File: internal/rest/server.go [hunk 5]
```diff
@@ -805,9 +805,13 @@ func (s *Server) GetProcessInstanceElementStatistics(ctx context.Context, reques
...
 		items := make(public.ElementStatistic, len(partition.GetStatistics()))
 		for _, entry := range partition.GetStatistics() {
+			completedCount := int(entry.GetCompletedCount())
+			terminatedCount := int(entry.GetTerminatedCount())
 			items[entry.GetElementId()] = public.ElementStatisticCounts{
-				ActiveCount:   int(entry.GetActiveCount()),
-				IncidentCount: int(entry.GetIncidentCount()),
+				ActiveCount:     int(entry.GetActiveCount()),
+				IncidentCount:   int(entry.GetIncidentCount()),
+				CompletedCount:  &completedCount,
```
Comment (alisku) [inline internal/rest/server.go:818]: Wouldn't it be better to make `completedCount` and `terminatedCount` required in YAML just like it is required for `ActiveCount` and `IncidentCount`. I believe the new properties are similar to the required old ones. Then you would not need to have the pointers logic

Comment (triskill) [reply internal/rest/server.go:818]: `GetProcessDefinitionElementStatistics` also uses `ElementStatisticCounts` structure, but without `completedCount` and `terminatedCount`. It can be mandatory, only when we implement these statistics also for process definitions, but we do not need it now.

**Review by alisku — APPROVED** [review]

File: test/e2e/process_instance_statistics_test.go [hunk 6]
```diff
@@ -107,6 +108,100 @@ func TestGetProcessInstanceElementStatistics(t *testing.T) {
...
+		// process completes synchronously: the terminate end event fires immediately and
+		// cancels the parallel service task token before any job worker can pick it up
+		instance, err := createProcessInstance(t, ptr.To(termDef.Key), map[string]any{})
+		require.NoError(t, err)
+
+		resp, err := app.restClient.GetProcessInstanceElementStatisticsWithResponse(t.Context(), instance.Key)
+		require.NoError(t, err)
+		require.NotNil(t, resp.JSON200)
+
+		// task-id was cancelled by the terminate end event
```
Comment (Kuzna) [inline test/e2e/process_instance_statistics_test.go]: Please remove the comments. Comments should explain why, not restate what the code already shows, so please use them only when needed → https://medium.com/codex/clean-code-comments-833e11a706dc

File: internal/sql/queries/process_instance.sql [hunk 7]
```diff
@@ -176,65 +176,59 @@ WHERE
...
+    LEFT JOIN process_instance AS sub_active
+        ON sub_active.parent_process_execution_token = et.key
+       AND sub_active.process_type = 4
+       AND sub_active.state = 1
+    LEFT JOIN process_instance AS sub_any
+        ON sub_any.parent_process_execution_token = et.key
+       AND sub_any.process_type = 4
+    WHERE et.process_instance_key IN (SELECT "key" FROM relevant_instances)
+      AND et.state IN (1, 2, 3, 4)
+    GROUP BY et.element_id
```
Comment (Kuzna) [inline internal/sql/queries/process_instance.sql:209]: Please check the SQL query, there is potential bug - If a single execution_token has multiple child process instances (e.g. a multi-instance call activity, or even just historical data where an instance was re-triggered), two LEFT JOINs into the same table will produce a Cartesian product — one execution_token row gets multiplied into N×M rows and the COUNT then inflates the numbers.Example: an execution_token has 1 active sub + 1 completed sub → sub_active matches 1 row, sub_any matches 2 rows → 2 result rows for the same token → completed/terminated count doubles.

**Review by Kuzna — CHANGES_REQUESTED** [review]

File: test/e2e/process_instance_statistics_test.go (hunk 6 above)
Comment (triskill) [reply test/e2e/process_instance_statistics_test.go]: comments removed

File: internal/sql/queries/process_instance.sql (hunk 7 above)
Comment (triskill) [reply internal/sql/queries/process_instance.sql:209]: I replaced double LEFT JOIN with `sub_flags` temporary table.

**Comment by Kuzna** [comment]
@triskill please add pagination tests for the first page, middle page, and last page, and also add tests for page size.

**Comment by triskill** [comment]
> @triskill please add pagination tests for the first page, middle page, and last page, and also add tests for page size.

Ok i added tests for pagination.

**Comment by triskill** [comment]
> @triskill please add pagination tests for the first page, middle page, and last page, and also add tests for page size.

Ok i added tests for pagination.

File: test/e2e/pagination_child_processes_test.go [hunk 8]
```diff
@@ -0,0 +1,109 @@
...
+						Size: ptr.To(int32(100)),
+					})
+				if err != nil || resp2.JSON200 == nil {
+					return false
+				}
+				count := 0
+				for _, p := range resp2.JSON200.Partitions {
+					count += len(p.Items)
+				}
+				return count >= childCount
```
Comment (Kuzna) [inline test/e2e/pagination_child_processes_test.go]: Please split this part of the code into small private methods with proper names, because it is currently hard to understand what the code is doing.

File: test/e2e/pagination_history_test.go [hunk 9]
```diff
@@ -0,0 +1,99 @@
...
+					for _, p := range resp.JSON200.Partitions {
+						for idx := range p.Items {
+							job := p.Items[idx]
+							if string(job.State) == "active" {
+								activeJob = &job
+								return true
+							}
+						}
+					}
+					return false
```
Comment (Kuzna) [inline test/e2e/pagination_history_test.go]: Please split this part of the code into small private methods with proper names, because it is currently hard to understand what the code is doing.

File: test/e2e/pagination_incidents_test.go [hunk 10]
```diff
@@ -0,0 +1,110 @@
...
+						"fail job %d: %s", job.Key, string(failResp.Body))
+				}
+			}
+
+			require.Eventually(t, func() bool {
+				resp, err := app.restClient.GetIncidentsWithResponse(t.Context(), instanceKey,
+					&zenclient.GetIncidentsParams{})
+				return err == nil && resp.JSON200 != nil && resp.JSON200.TotalCount >= totalIncidents
+			}, 10*time.Second, 200*time.Millisecond,
+				"all %d incidents should appear", totalIncidents)
```
Comment (Kuzna) [inline test/e2e/pagination_incidents_test.go]: Please split this part of the code into small private methods with proper names, because it is currently hard to understand what the code is doing.

File: test/e2e/pagination_jobs_test.go [hunk 11]
```diff
@@ -0,0 +1,164 @@
...
+					for _, j := range p.Items {
+						if subInstanceKey == 0 {
+							subInstanceKey = j.ProcessInstanceKey
+						}
+						if j.ProcessInstanceKey == subInstanceKey {
+							count++
+						}
+					}
+				}
+				return count >= jobCount
```
Comment (Kuzna) [inline test/e2e/pagination_jobs_test.go]: Please split this part of the code into small private methods with proper names, because it is currently hard to understand what the code is doing.

File: test/e2e/pagination_dmn_test.go [hunk 12]
```diff
@@ -0,0 +1,142 @@
...
+					})
+				if err != nil || resp.JSON200 == nil {
+					return false
+				}
+				count := 0
+				for _, p := range resp.JSON200.Partitions {
+					count += len(p.Items)
+				}
+				return count >= 11
+			}, 10*time.Second, 200*time.Millisecond, "11 decision instances should be created")
```
Comment (Kuzna) [inline test/e2e/pagination_dmn_test.go]: Please split this part of the code into small private methods with proper names, because it is currently hard to understand what the code is doing.

**Review by Kuzna — CHANGES_REQUESTED** [review]

File: test/e2e/pagination_dmn_test.go (hunk 12 above)
Comment (triskill) [reply test/e2e/pagination_dmn_test.go]: Ok, done.

File: test/e2e/pagination_jobs_test.go (hunk 11 above)
Comment (triskill) [reply test/e2e/pagination_jobs_test.go]: Ok, done.

File: test/e2e/pagination_incidents_test.go (hunk 10 above)
Comment (triskill) [reply test/e2e/pagination_incidents_test.go]: Ok, done.

File: test/e2e/pagination_history_test.go (hunk 9 above)
Comment (triskill) [reply test/e2e/pagination_history_test.go]: Ok, done.

File: test/e2e/pagination_jobs_test.go (hunk 11 above)
Comment (triskill) [reply test/e2e/pagination_jobs_test.go]: Ok, done.

File: test/e2e/pagination_child_processes_test.go (hunk 8 above)
Comment (triskill) [reply test/e2e/pagination_child_processes_test.go]: Ok, done.

**Review by Kuzna — APPROVED** [review]
