### PR TITLE
Fix/484 no process instance key and flow element instance key is saved in decision instance

### LINKED ISSUE #484: No process_instance_key and flow_element_instance_key is saved in decision_instance
### Description

I expect the relations will be created: 
decision_instance -> process_instance
decision_instance -> flow_element_instance

### Steps to Reproduce

Run any process with business rule task.

### Environment

_No response_

### Expected Behavior

_No response_

### PR DESCRIPTION
**Pull request by triskill**
closes #484

### CODE REVIEW

File: pkg/bpmn/engine.go [hunk 1]
```diff
@@ -697,6 +697,12 @@ func (engine *Engine) handleLocalBusinessRuleTask(
 		},
 	)
 
+	err := batch.Flush(ctx) // doing this to have saved foreign key flow_element_instance_key on decision_instance
+	if err != nil {
+		instance.ProcessInstance().State = runtime.ActivityStateFailed
+		return runtime.ActivityStateFailed, fmt.Errorf("failed to flush batch before evaluating decision: %w", err)
+	}
```
[the remark this answers is not in the document]
Comment (triskill) [reply pkg/bpmn/engine.go]: ok, i added new batch

File: internal/sql/migrations/0002_remove_decision_instance_fk.down.sql [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+    FOREIGN KEY (decision_definition_key) REFERENCES decision_definition(key),
+    FOREIGN KEY (process_instance_key) REFERENCES process_instance(key),
+    FOREIGN KEY (flow_element_instance_key) REFERENCES flow_element_instance(key)
+);
+
+INSERT INTO decision_instance_new SELECT * FROM decision_instance;
+
+DROP TABLE decision_instance;
+
+ALTER TABLE decision_instance_new RENAME TO decision_instance;
```
Comment (Kuzna) [inline internal/sql/migrations/0002_remove_decision_instance_fk.down.sql:24]: This should be wrapped in BEGIN/COMMIT to avoid data loss if something fails between DROP and RENAME.

File: internal/sql/migrations/0002_remove_decision_instance_fk.up.sql [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+    FOREIGN KEY (dmn_resource_definition_key) REFERENCES dmn_resource_definition(key),
+    FOREIGN KEY (decision_definition_key) REFERENCES decision_definition(key),
+    FOREIGN KEY (process_instance_key) REFERENCES process_instance(key)
+);
+
+INSERT INTO decision_instance_new SELECT * FROM decision_instance;
+
+DROP TABLE decision_instance;
+
+ALTER TABLE decision_instance_new RENAME TO decision_instance;
```
Comment (Kuzna) [inline internal/sql/migrations/0002_remove_decision_instance_fk.up.sql:24]: This should be wrapped in BEGIN/COMMIT to avoid data loss if something fails between DROP and RENAME.

**Review by Kuzna — CHANGES_REQUESTED** [review]

File: internal/sql/migrations/0002_remove_decision_instance_fk.down.sql (hunk 2 above)
Comment (triskill) [reply internal/sql/migrations/0002_remove_decision_instance_fk.down.sql:24]: Ok, i wrapped it in transaction and amended. Thanks.

File: internal/sql/migrations/0002_remove_decision_instance_fk.up.sql (hunk 3 above)
Comment (triskill) [reply internal/sql/migrations/0002_remove_decision_instance_fk.up.sql:24]: Ok, i wrapped it in transaction and amended. Thanks.

File: internal/sql/migrations/0002_remove_decision_instance_fk.down.sql (hunk 2 above)
Comment (triskill) [reply internal/sql/migrations/0002_remove_decision_instance_fk.down.sql:24]: Actually it fails:     `partition_persistence_test.go:123: failed to run migrations: failed to execute migration 0002_remove_decision_instance_fk.up.sql: cannot start a transaction within a transaction`
It looks like it is transaction by default.

File: internal/sql/migrations/0002_remove_decision_instance_fk.up.sql (hunk 3 above)
Comment (triskill) [reply internal/sql/migrations/0002_remove_decision_instance_fk.up.sql:24]: Actually it fails:     `partition_persistence_test.go:123: failed to run migrations: failed to execute migration 0002_remove_decision_instance_fk.up.sql: cannot start a transaction within a transaction`
It looks like it is transaction by default.

File: pkg/bpmn/engine.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (triskill) [reply pkg/bpmn/engine.go]: This was removed. Instead this, foreign key was removed from `flow_element_instance_key`

File: internal/sql/migrations/0002_remove_decision_instance_fk.down.sql (hunk 2 above)
Comment (Kuzna) [reply internal/sql/migrations/0002_remove_decision_instance_fk.down.sql:24]: Then it’s OK, and sorry for the misunderstanding.

**Review by Kuzna — APPROVED** [review]
