### PR TITLE
fix(518): recover from timer panics and fail fast on instance start

### LINKED ISSUE #518: Nil pointer dereference in Engine.CreateInstance when createInstance fails
### Description

When `Engine.CreateInstance` is called and the internal `createInstance` call returns an error, the error is silently discarded and the code proceeds to dereference a nil/invalid instance, causing a panic.

In `pkg/bpmn/engine_api.go` (CreateInstance):

```go
instance, executionTokens, err := engine.createInstance(...)
err = batch.Flush(ctx) // overwrites the original err without checking it
if err != nil {
    return nil, fmt.Errorf("failed to start process instance: %w", err)
}
```

stacktrace
```
panic recovered in gRPC handler /cluster.ZenService/CreateInstance:
runtime error: invalid memory address or nil pointer dereference
pkg/bpmn/engine_api.go:326 (*Engine).CreateInstance
pkg/bpmn/engine_api.go:301 (*Engine).CreateInstanceByKey
internal/cluster/server/server.go:283 (*Server).CreateInstance
```

### Steps to Reproduce

Send a CreateInstance gRPC request (cluster.ZenService/CreateInstance) that causes the internal engine.createInstance(...) call to fail (e.g. invalid process definition or persistence error).
Observe the server logs.

### Environment

macOS

### Expected Behavior

If createInstance returns an error, CreateInstance should return that error to the caller without panicking.

### PR DESCRIPTION
**Pull request by Kuzna**
- recover from panics in timer processing and log stack traces
- keep the timer manager loop resilient to runtime failures
- Replaced inline logic for token termination with `terminateExecutionToken`.
- Added `terminateActiveJobsForToken` for job termination and `resolveIncidentsForToken` for incident resolution.
- Improved code readability and modularity.

### CODE REVIEW

File: pkg/bpmn/timer_manager.go [hunk 1]
```diff
@@ -88,37 +89,53 @@ func (tm *timerManager) removeTimer(timer runtime.Timer) {
...
+		tm.processTimerFunc(context.Background(), timer)
+		tm.mu.Lock()
+		for i, item := range tm.waitingTimers {
+			if item.timer.Key == timer.Key {
+				tm.waitingTimers = append(tm.waitingTimers[:i], tm.waitingTimers[i+1:]...)
+				break
 			}
-			tm.nextPoll = t.Add(tm.pollTimerDelay)
 		}
+		tm.mu.Unlock()
```
[the remark this answers is not in the document]
Comment (Kuzna) [reply pkg/bpmn/timer_manager.go]: fixed

File: pkg/bpmn/engine_api.go [hunk 2]
```diff
@@ -300,6 +300,9 @@ func (engine *Engine) CreateInstance(ctx context.Context, process *runtime.Proce
 		runtime.NewVariableHolder(nil, variableContext),
 		&runtime.DefaultProcessInstance{},
 	)
+	if err != nil {
+		return nil, fmt.Errorf("failed to start process instance: %w", err)
+	}
 	err = batch.Flush(ctx)
 	if err != nil {
 		return nil, fmt.Errorf("failed to start process instance: %w", err)
```
Comment (klajmajk) [inline pkg/bpmn/engine_api.go:325]: this should be failed to flush

File: pkg/bpmn/timer_api.go [hunk 3]
```diff
@@ -43,7 +48,7 @@ func (engine *Engine) TriggerTimer(ctx context.Context, timer runtime.Timer) (
 
 	currentToken := timer.Token
 	tokenNode := instance.ProcessInstance().Definition.Definitions.Process.GetFlowNodeById(currentToken.ElementId)
-	if tokenNode.GetId() == "" {
+	if tokenNode == nil || tokenNode.GetId() == "" {
 		return nil, nil, errors.Join(newEngineErrorf("failed to find timer node with elementId: %s", timer.ElementId), err)
```
Comment (klajmajk) [inline pkg/bpmn/timer_api.go]: No need to join err as it is always nil

File: pkg/bpmn/timer_api.go [hunk 4]
```diff
@@ -35,6 +37,9 @@ func (engine *Engine) TriggerTimer(ctx context.Context, timer runtime.Timer) (
 			completeTimerSpan.SetStatus(codes.Error, retErr.Error())
 		}
 		completeTimerSpan.End()
+		if r := recover(); r != nil {
```
Comment (klajmajk) [inline pkg/bpmn/timer_api.go]: this should run before the span as we want tothe panic to be recored on the span and setting an error status before ending it.

**Review by klajmajk — CHANGES_REQUESTED** [review]

File: pkg/bpmn/engine_api.go (hunk 2 above)
Comment (Kuzna) [reply pkg/bpmn/engine_api.go:325]: This fix is no longer needed, as the method body has already been changed in the start timer events PR.

File: pkg/bpmn/timer_api.go (hunk 4 above)
Comment (Kuzna) [reply pkg/bpmn/timer_api.go]: fixed

File: pkg/bpmn/timer_api.go (hunk 3 above)
Comment (Kuzna) [reply pkg/bpmn/timer_api.go]: Also fixed a few other places in the same method

**Review by klajmajk — APPROVED** [review]
